export const projects = [
  {
    title: "Musée Maritime",
    images: ["./public/museem.webp", "./public/mm2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/musee-maritime",
    tags: ["REBRANDING", "DA", "PRINT"],
  },
  {
    title: "Moonrush",
    images: ["./public/moonrush.webp", "./public/mr2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/moonrush",
    tags: ["BRANDING", "DESIGN", "DA"],
  },
  {
    title: "Suapse",
    images: ["./public/suapse.webp", "./public/suapse2.webp"],
    year: 2024,
    href: "https://works.elytra-studio.fr/suapse",
    tags: ["ILLUSTRATION", "AFFICHAGE", "DESIGN"],
  },
  {
    title: "TMG",
    images: ["./public/tmg.webp", "./public/tmg2.webp"],
    year: 2024,
    href: "https://works.elytra-studio.fr/tmg",
    tags: ["REBRANDING", "AFFICHAGE", "PRINT"],
  },
  {
    title: "Fête de la musique",
    images: ["./public/fmusique.webp", "./public/fdlm2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/fete-musique-2025",
    tags: ["ILLUSTRATION", "AFFICHAGE", "PRINT"],
  },
  {
    title: "Basique",
    images: ["./public/basique.webp", "./public/basique2.webp"],
    year: 2024,
    href: "https://works.elytra-studio.fr/basique",
    tags: ["BRANDING", "PACKAGING", "ILLUSTRATION"],
  },
  {
    title: "Châtelaillon",
    images: ["./public/chatel.webp", "./public/chatel2.webp"],
    year: 2024,
    href: "https://works.elytra-studio.fr/chatelaillon",
    tags: ["PRINT", "AFFICHAGE", "FICTIF"],
  },
  {
    title: "Book Tons",
    images: ["./public/tonbook.webp", "./public/bookt2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/livre-tons",
    tags: ["ÉDITION", "PRINT", "DESIGN"],
  },
  {
    title: "Marché Créatif",
    images: ["./public/marche.webp", "./public/marche2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/marche-creatif",
    tags: ["PRINT", "AFFICHAGE", "DESIGN"],
  },
  {
    title: "Spontex",
    images: ["./public/spontex.webp", "./public/spontex2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/spontex",
    tags: ["DA", "REBRANDING", "DESIGN"],
  },
  {
    title: "Francofolies",
    images: ["./public/franco.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/francofolies",
    tags: ["MOTION", "DA", "ILLUSTRATION"],
  },
  {
    title: "Pixii Festival",
    images: ["./public/pixii.webp", "./public/pixii2.webp"],
    year: 2024,
    href: "https://works.elytra-studio.fr/pixii-festival",
    tags: ["REBRANDING", "DESIGN", "COMMUNICATION"],
  },
  {
    title: "Lyon Biennale",
    images: ["./public/lyonbien.webp", "./public/lyonb2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/biennale-lyon",
    tags: ["AFFICHE", "PRINT", "FICTIF"],
  },
  {
    title: "Neonflow",
    images: ["./public/neonflow.webp", "./public/neonflow2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/neon-flow",
    tags: ["AFFICHAGE", "PRINT", "DESIGN"],
  },
  {
    title: "Wilee",
    images: ["./public/wilee.webp", "./public/wilee2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/wilee",
    tags: ["DA", "REBRANDING", "DESIGN"],
  },
  {
    title: "Synthèse",
    images: ["./public/synthese.webp", "./public/synt2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/synthese-humaine",
    tags: ["PRINT", "AFFICHAGE", "PHOTO"],
  },
  {
    title: "Serre Rochelaise",
    images: ["./public/bota.webp", "./public/bota2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/serre-rochelaise",
    tags: ["BRANDING", "PRINT", "CAMPAIGN"],
  },
  {
    title: "Rouge aux lèvres",
    images: ["./public/beaujolais.webp", "./public/beaujolais2.webp"],
    year: 2024,
    href: "https://works.elytra-studio.fr/rouge-aux-levres",
    tags: ["ILLUSTRATION", "AFFICHAGE", "PRINT"],
  },
  {
    title: "City guide",
    images: ["./public/maplr.webp", "./public/maplr2.webp"],
    year: 2024,
    href: "https://works.elytra-studio.fr/city-guide",
    tags: ["ILLUSTRATION", "ÉDITION", "DESIGN"],
  },
  {
    title: "Almanak",
    images: ["./public/almanak.webp", "./public/almanak2.webp"],
    year: 2024,
    href: "https://works.elytra-studio.fr/almanak-communication",
    tags: ["ÉDITION", "PRINT", "DESIGN"],
  },
  {
    title: "Bal des formes",
    images: ["./public/baldf.webp", "./public/baldf2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/bal-des-formes",
    tags: ["PRINT", "AFFICHAGE", "DESIGN"],
  },
  {
    title: "Ideocentre",
    images: ["./public/ideo.webp", "./public/ideo2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/ideocentre",
    tags: ["BRANDING", "AFFICHAGE", "PRINT"],
  },
  {
    title: "Ricoré",
    images: ["./public/rico.webp", "./public/rico2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/ricore",
    tags: ["REBRANDING", "DA", "FICTIF"],
  },
  {
    title: "Graphika",
    images: ["./public/graphika.webp", "./public/graphika2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/graphika",
    tags: ["AFFICHES", "PRINT", "BRANDING"],
  },
  {
    title: "Redbull campaign",
    images: ["./public/red.webp", "./public/red2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/redbull-campaign",
    tags: ["AI", "PHOTO", "MARKETING"],
  },
  {
    title: "Archipel",
    images: ["./public/archipel.webp", "./public/archipel2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/archipel-vr",
    tags: ["AFFICHES", "PRINT", "MOTION"],
  },
  {
    title: "Théâtre de Belleville",
    images: ["./public/bellev.webp", "./public/belleville.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/belleville",
    tags: ["CAMPAIGN", "FASHION"],
  },
  {
    title: "Fête de la Saint-Jean",
    images: ["./public/saintjean.webp", "./public/saintj2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/saint-jean",
    tags: ["ILLUSTRATION", "AFFICHAGE", "FICTIF"],
  },  
  {
    title: "Tryyland",
    images: ["./public/tryyland.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/tryyland",
    tags: ["EBOOK", "ÉDITION", "WEB"],
  },
  {
    title: "Michel Crépeau",
    images: ["./public/mediatheque.webp", "./public/mc2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/mediatheque-michel-crepeau",
    tags: ["REBRANDING", "DA", "DESIGN"],
  },
  {
    title: "Atelier Écriture",
    images: ["./public/ecriture.webp", "./public/ecriture2.webp"],
    year: 2025,
    href: "https://works.elytra-studio.fr/ecriture-atelier",
    tags: ["ILLUSTRATION", "AFFICHAGE", "PRINT"],
  },
];